### ISSUE TITLE
Activate AppVeyor

### ISSUE THREAD

**Issue by dhermes** [kirbyfan64/python.pypy#10]
@kirbyfan64 There are two issues. 

1. When I activated AppVeyor for this project, the [URL][1] had my username in it rather than the actual URL of this project (i.e. yours)
1. The webhooks to actually run builds on commits didn't seem to get set-up here, likely because I'm not an admin here. Care to set up AppVeyor / make me an admin?

[1]: https://ci.appveyor.com/project/dhermes/chocolatey-pypy/history

**Comment by refi64** [comment]
Off the computer for the day, but I'll definitely take a look at this tomorrow.

**Comment by dhermes** [comment]
@kirbyfan64 Did you have a chance to do this?

**Comment by refi64** [comment]
@dhermes Ack sorry, forgot about it. I just did it now: https://ci.appveyor.com/project/kirbyfan64/chocolatey-pypy

**Comment by dhermes** [comment]
Great. I'll update the relevant links in PR #12.
