### ISSUE TITLE
Change icon URL

### ISSUE THREAD

**Issue by FranklinYu** [kirbyfan64/python.pypy#15]
Currently both packages have icon

`https://rawgit.com/kirbyfan64/chocolatey-pypy/master/pypy-icon.png`

This URL has 3 issues:

 1. [RawGit is not for JPEG or PNG images](https://github.com/rgrove/rawgit/blob/master/FAQ.md#why-does-rawgit-redirect-requests-for-jpg-png-and-other-image-files-to-github).
 2. RawGit is retiring.
 3. Chocolatey package icons typically pin the commit instead of pointing to a branch like `master`, to improve caching and performance.

I propose to replace it with

https://raw.githubusercontent.com/kirbyfan64/chocolatey-pypy/abc48080ebf1456e20dce47cdcf4698ac0c78a42/pypy-icon.png

Ideas?

**Comment by dhermes** [comment]
I am :+1: on this, though version-pinning seems more desirable:

https://raw.githubusercontent.com/kirbyfan64/chocolatey-pypy/6.0.0/pypy-icon.png

**Comment by FranklinYu** [comment]
Wasn't aware of the Git tag! Of course that's the best solution.
