### ISSUE TITLE
PyPy3?

### ISSUE THREAD

**Issue by altendky** [kirbyfan64/python.pypy#4]
Any interest in maintaining a PyPy3 copy of this?  If not I might find time to fork and handle it but it seems like it might be a quick thing to do.

Cheers,
-kyle

**Comment by dhermes** [comment]
@altendky I may take a stab at it if you don't want to

**Comment by altendky** [comment]
@dhermes, I haven't popped down my stack of other tickets and PRs back to here yet so... Go for it :]  not that I know chocolatey but feel free to ping me if you want another set of eyes on something.

**Comment by dhermes** [comment]
https://chocolatey.org/packages/python.pypy3/6.0.0 pending, source at https://github.com/dhermes/python.pypy3

I added an AppVeyor configuration to build and verify the `*.nupkg` file (my only Windows install is on a partition on my work machine and it's no fun to shut down to run Windows commands).

**Comment by dhermes** [comment]
@altendky I'm happy to add you as a collaborator there if you like.

**Comment by altendky** [comment]
@dhermes, thanks for setting that up. Now I have to figure out what's wrong with virtualenv.

https://ci.appveyor.com/project/ebroecker/canmatrix/build/job/osmldoit63ujycye

**Comment by dhermes** [comment]
For posterity / anyone else who comes across this, the package is in https://chocolatey.org/packages/pypy3 (i.e. the name changed from `python.pypy3` to just `pypy3`)
