### ISSUE TITLE
choco package doesn't reflect changes here

### ISSUE THREAD

**Issue by dhermes** [kirbyfan64/python.pypy#5]
The current latest version on https://chocolatey.org/packages/python.pypy is `5.9`:

![screenshot from 2018-09-19 21-44-31](https://user-images.githubusercontent.com/520669/45796404-36a7aa80-bc55-11e8-8e8c-34b285318c95.png)

**Comment by refi64** [comment]
Err, I might have forgotten to submit it... 😅

**Comment by dhermes** [comment]
Fixed with https://chocolatey.org/packages/python.pypy/6.0
