### ISSUE TITLE
Change GitHub repo name

### ISSUE THREAD

**Issue by dhermes** [kirbyfan64/python.pypy#7]
@kirbyfan64 WDYT of renaming this repo to `chocolatey-pypy` to match https://github.com/dhermes/chocolatey-pypy3 and to make it clear that this is for the Chocolatey package?

**Comment by refi64** [comment]
Done.

**Comment by refi64** [comment]
Actually maybe I should do chocolatey-pypy2 instead, considering the general shift towards Python 3...

**Comment by dhermes** [comment]
Nice, I just realized you did this :grin:
